import Lean
import Paralean.Driver

/-!
Replay of stored groups in one process.

* **Source replay** rebuilds a frontend environment from the base imports by re-elaborating
  the closure's capsules in order, and checks that every re-elaborated command produces the
  stored declaration ID.
* **Kernel replay** starts from the base kernel environment and adds the *stored* terms
  (decoded from the content-addressed objects) with the stock kernel (`addDeclCore`, always
  checked). Reserved names are never taken from the store: they are re-realized from the
  pinned base group in the source-replayed environment and kernel-checked on insertion.
-/

namespace Paralean
open Lean Elab

/-- Synthetic header importing the given base modules. -/
def headerFor (imports : Array Name) : String :=
  String.join (imports.toList.map fun m => s!"import {m}\n")

structure SourceReplay where
  sess : Session
  baseEnv : Environment
  results : Array ReplayRes
  /-- (package id, local identity) ↦ Lean name in the replayed environment. -/
  names : Std.HashMap (String × Name) Name

unsafe def sourceReplay (cat : Catalog) (gids : Array String) (imports : Array Name)
    (module? : Option Name := none) (conservative := false)
    (materialize? : Option Materializer := none) : IO SourceReplay := do
  -- same module root as the captured groups: Lean's generated names depend on it
  let module := module?.getD <| match gids[0]? with
    | some g => (cat.get! g).capsule.module.getRoot ++ `ParaleanReplay
    | none => `ParaleanReplay
  let isModule := gids.any fun g => (cat.get! g).capsule.isModule
  -- module system: reuse the import lines as written (`meta import`, `public import`, ...)
  let specs := gids.foldl (fun acc g => (cat.get! g).capsule.importSpecs.foldl
    (fun acc sp => if acc.contains sp then acc else acc.push sp) acc) #[]
  let hdr := if isModule then
      "module\n" ++ String.join (specs.toList.map (· ++ "\n"))
    else headerFor imports
  -- initializer groups (and their closure) are imported as stock-built modules
  let initGs := initClosure cat gids
  let mut matRes : Option MatResult := none
  if let some mat := materialize? then
    if !initGs.isEmpty then
      let mr ← mat cat initGs
      if !mr.covered.isEmpty then matRes := some mr
  let (sess0, inputCtx, _, imps, hdrDiags, _) ← openSession hdr "<replay>" module
    (extraImports := (matRes.map (·.imports)).getD #[]) (arts := (matRes.map (·.arts)).getD {})
  unless hdrDiags.isEmpty do
    throw <| IO.userError s!"replay header failed: {hdrDiags.map toString}"
  let covered := (matRes.map (·.covered)).getD #[]
  let sess0 := match matRes with
    | some mr => { sess0 with index := mr.identOf sess0.cmdState.env, pkgs := mr.pkgs }
    | none => sess0
  let fc0 : FileCtx := {
    workspace := "<replay>", file := "<replay>", module, imports := imps, input := hdr
    fileMap := inputCtx.fileMap, baseEnv := sess0.cmdState.env }
  let mut sess := sess0
  let mut results := #[]
  for gid in gids do
    let g := cat.get! gid
    if covered.contains gid then
      results := results.push { gid, ok := true, materialized := true, diags := #[{
        severity := "info", code := "materialized", file := g.capsule.file, line := g.capsule.startLine
        msg := "initializer group imported as a stock-built module" }] }
      continue
    let deps := relocatedDepsOf cat g conservative
    let src := renderCapsule g deps
    let (sess', res) ← replayCapsule sess fc0 g src (capsuleTextOffset g deps)
    sess := sess'
    results := results.push res
  let mut names := {}
  for (n, key) in sess.index.toArray do
    names := names.insert key n
  return { sess, baseEnv := sess0.cmdState.env, results, names }

/-! ## Kernel replay -/

structure KernelRes where
  gid : String
  ok : Bool
  added : Nat
  realized : Nat
  diags : Array Diag
  /-- Transitive axioms of the group's members, from the kernel environment. -/
  axioms : Array Name := #[]

def kernelExMsg (e : Kernel.Exception) : IO String := do
  (e.toMessageData {}).toString

/-- Declarations to add for a decoded group, in dependency order. Recursors and
constructors are generated by the kernel from the inductive declaration. -/
def declsOf (members : Array (Name × NameClass × ConstantInfo)) : Except String (Array Declaration) := do
  let infos : Std.HashMap Name ConstantInfo := members.foldl (fun m (_, _, ci) => m.insert ci.name ci) {}
  -- units: inductive blocks, mutual unsafe defs, single declarations
  let mut units : Array (Array Name × Declaration) := #[]
  let mut done : NameSet := {}
  for (_, _, ci) in members do
    if done.contains ci.name then continue
    match ci with
    | .inductInfo v =>
      let mut types := #[]
      for n in v.all do
        let some (.inductInfo iv) := infos[n]? | throw s!"inductive block member {n} missing"
        let mut ctors := #[]
        for c in iv.ctors do
          let some (.ctorInfo cv) := infos[c]? | throw s!"constructor {c} missing"
          ctors := ctors.push { name := c, type := cv.type : Constructor }
        types := types.push { name := n, type := iv.type, ctors := ctors.toList : InductiveType }
        done := done.insert n
      let names := v.all.toArray ++ (types.flatMap fun t => t.ctors.toArray.map (·.name))
      units := units.push (names, .inductDecl v.levelParams v.numParams types.toList v.isUnsafe)
    | .ctorInfo _ | .recInfo _ => pure ()
    | .defnInfo v =>
      if v.safety != .safe then
        let mut ds := #[]
        -- `all` may name constants outside the group (e.g. `compile_inductive%` makes an
        -- unsafe implementation whose `all` is the inductive); only group members join
        for n in v.all do
          if let some (.defnInfo dv) := infos[n]? then
            ds := ds.push dv
            done := done.insert n
        if ds.isEmpty then ds := #[v]; done := done.insert ci.name
        units := units.push (v.all.toArray, .mutualDefnDecl ds.toList)
      else
        done := done.insert ci.name
        units := units.push (#[ci.name], .defnDecl v)
    | .thmInfo v => done := done.insert ci.name; units := units.push (#[ci.name], .thmDecl v)
    | .opaqueInfo v => done := done.insert ci.name; units := units.push (#[ci.name], .opaqueDecl v)
    | .axiomInfo v => done := done.insert ci.name; units := units.push (#[ci.name], .axiomDecl v)
    | .quotInfo _ => done := done.insert ci.name; units := units.push (#[ci.name], .quotDecl)
  -- topological order over in-group references
  let unitOf : Std.HashMap Name Nat := units.size.fold (init := {}) fun i _ m =>
    units[i]!.1.foldl (fun m n => m.insert n i) m
  let usedBy (i : Nat) : Array Nat := Id.run do
    let mut out := #[]
    for n in units[i]!.1 do
      if let some ci := infos[n]? then
        for c in ci.getUsedConstantsAsSet do
          -- recursors of in-group inductives count as the inductive's unit
          let c' := if let some (.recInfo rv) := infos[c]? then rv.all.head! else c
          if let some j := unitOf[c']? then
            if j != i && !out.contains j then out := out.push j
    return out
  let mut order := #[]
  let mut state : Array Nat := Array.replicate units.size 0  -- 0 new, 1 active, 2 done
  for i0 in [0:units.size] do
    if state[i0]! != 0 then continue
    let mut stack : Array (Nat × Bool) := #[(i0, false)]
    while !stack.isEmpty do
      let (i, post) := stack.back!
      stack := stack.pop
      if post then
        state := state.set! i 2; order := order.push i
      else if state[i]! == 0 then
        state := state.set! i 1
        stack := stack.push (i, true)
        for j in usedBy i do
          if state[j]! == 0 then stack := stack.push (j, false)
          else if state[j]! == 1 then throw "cyclic references inside a group"
  return order.map (units[·]!.2)

/-- Lean name of a `Ref` in the source-replayed environment. -/
partial def replayName (sr : SourceReplay) (selfGid : String) (env : Environment) : Ref → Except String Name
  | .base n => pure n
  -- Without a source-replayed spelling (e.g. the capsule failed to re-elaborate), the
  -- kernel validator still runs, using the identity name itself.
  | .self l => pure (sr.names[(selfGid, l)]?.getD l)
  | .dep g l => pure (sr.names[(g, l)]?.getD l)
  | .res r s => do
    let b ← replayName sr selfGid env r
    let cands := [b ++ s, mkPrivateNameCore env.mainModule (privateToUserName b ++ s),
                  mkPrivateNameCore env.mainModule (b ++ s)]
    match cands.find? (fun c => isReservedName env c && env.contains c) with
    | some c => pure c
    | none => pure (b ++ s)

/-- Re-realize reserved name `n` in the frontend environment (runs the registered
reserved-name action, as a consumer would). -/
unsafe def realizeIn (sess : Session) (n : Name) : IO (Session × Option ConstantInfo) := do
  let env := sess.cmdState.env
  if let some ci := env.find? n then return (sess, some ci)
  let ctx : Core.Context := { fileName := "<realize>", fileMap := default, options := hostOptions }
  let st : Core.State := { env }
  try
    let (_, st') ← (executeReservedNameAction n).toIO ctx st
    let sess := { sess with cmdState := { sess.cmdState with env := st'.env } }
    return (sess, st'.env.find? n)
  catch _ => return (sess, none)

/-- Transitive axioms of `n` in the kernel environment `kenv`. Constants of the base
environment are answered by Lean's `collectAxioms` (which follows original declaration
kinds across `module` boundaries); everything else is walked. -/
unsafe def kernelAxioms (baseEnv : Environment) (kenv : Kernel.Environment)
    (cache : Std.HashMap Name (Array Name)) (n : Name) :
    IO (Array Name × Std.HashMap Name (Array Name)) := do
  let mut cache := cache
  -- iterative post-order walk
  let mut stack : Array (Name × Bool) := #[(n, false)]
  while !stack.isEmpty do
    let (c, post) := stack.back!
    stack := stack.pop
    if cache.contains c && !post then continue
    if (baseEnv.getModuleIdxFor? c).isSome then
      let ctx : Core.Context := { fileName := "<axioms>", fileMap := default }
      let (a, _) ← (Lean.collectAxioms (m := CoreM) c).toIO ctx { env := baseEnv }
      cache := cache.insert c a
      continue
    match kenv.find? c with
    | none => cache := cache.insert c #[]
    | some ci =>
      let used := ci.getUsedConstantsAsSet.toArray
      if !post then
        cache := cache.insert c #[]   -- cycle guard (inductive ↔ constructors)
        stack := stack.push (c, true)
        for u in used do
          unless cache.contains u do stack := stack.push (u, false)
      else
        let mut acc : Array Name := if ci matches .axiomInfo _ then #[c] else #[]
        for u in used do
          for a in cache.getD u #[] do
            unless acc.contains a do acc := acc.push a
        cache := cache.insert c acc
  return (cache.getD n #[], cache)

unsafe def kernelReplay (store : Store) (cat : Catalog) (gids : Array String) (sr : SourceReplay) :
    IO (Array KernelRes × SourceReplay) := do
  let mut kenv := sr.baseEnv.toKernelEnv
  let mut axCache : Std.HashMap Name (Array Name) := {}
  let mut sr := sr
  let mut out := #[]
  let maxHB : USize := (Core.getMaxHeartbeats {}).toUSize
  let maxRec : USize := (maxRecDepth.get {}).toUSize
  for gid in gids do
    let g := cat.get! gid
    if sr.results.any (fun r => r.gid == gid && r.materialized) then
      -- its constants are in the base environment, checked by the stock build
      out := out.push { gid, ok := true, added := 0, realized := 0, diags := #[] }
      continue
    let mut diags : Array Diag := #[]
    let mk (code msg : String) : Diag :=
      { severity := "reject", code, msg, file := g.capsule.file, line := g.capsule.startLine }
    let bytes ← store.getObject g.declId
    for d in g.deps ++ g.feDeps do
      if out.any (fun (k : KernelRes) => k.gid == d && !k.ok) then
        diags := diags.push (mk "rejected-dep" s!"depends on group {d.take 12}, which the validator rejected")
    let env := sr.sess.cmdState.env
    match decodeGroup bytes (cat.unwire g) (replayName sr gid env) with
    | .error e =>
      out := out.push { gid, ok := false, added := 0, realized := 0, diags := #[mk "decode" e] }
    | .ok dg =>
      -- Reserved dependencies: re-realize them in the frontend environment (never from the
      -- store) and add them, interleaved with the group's own declarations, to the kernel.
      let memberNames : NameSet := dg.members.foldl (fun s (_, _, ci) => s.insert ci.name) {}
      let mut todo : Array Name := #[]
      for r in dg.refs do
        if let .res .. := r then
          match replayName sr gid sr.sess.cmdState.env r with
          | .ok n => todo := todo.push n
          | .error e => diags := diags.push (mk "reserved-name" e)
      let mut extra : Array ConstantInfo := #[]
      let mut seen : NameSet := {}
      while !todo.isEmpty do
        let n := todo.back!
        todo := todo.pop
        if seen.contains n || (kenv.find? n).isSome || memberNames.contains n then continue
        seen := seen.insert n
        let (sess', ci?) ← realizeIn sr.sess n
        sr := { sr with sess := sess' }
        let some ci := ci? | do
          diags := diags.push (mk "re-realize" s!"cannot re-realize reserved name {n}")
          continue
        extra := extra.push ci
        for c in ci.getUsedConstantsAsSet do
          unless (kenv.find? c).isSome || memberNames.contains c || seen.contains c do
            if isReservedName sr.sess.cmdState.env c then todo := todo.push c
            else diags := diags.push (mk "re-realize"
              s!"realized {n} needs {c}, which is neither reserved nor already replayed")
      let mut added := 0
      let nReal := extra.size
      match declsOf (dg.members ++ extra.map fun ci => (ci.name, NameClass.scoped, ci)) with
      | .error e => diags := diags.push (mk "decls" e)
      | .ok ds =>
        for d in ds do
          match Kernel.Environment.addDeclCore kenv maxHB maxRec d none with
          | .ok k => kenv := k; added := added + 1
          | .error e => diags := diags.push (mk "kernel" s!"{d.getNames}: {← kernelExMsg e}")
        -- kernel-generated recursors must equal the transported ones
        for (_, _, ci) in dg.members do
          if let .recInfo _ := ci then
            match kenv.find? ci.name with
            | some ci' =>
              unless ci'.type == ci.type && ci'.levelParams == ci.levelParams do
                diags := diags.push (mk "recursor" s!"regenerated {ci.name} differs")
            | none => diags := diags.push (mk "recursor" s!"{ci.name} not generated")
      -- Axiom audit of the transported closure, independent of any worker summary:
      -- walk the kernel environment; base constants use Lean's precomputed axiom data.
      let mut groupAxioms : Array Name := #[]
      for (_, _, ci) in dg.members do
        let (axs, cache') ← kernelAxioms sr.baseEnv kenv axCache ci.name
        axCache := cache'
        for a in axs do
          unless groupAxioms.contains a do groupAxioms := groupAxioms.push a
        for a in axs do
          unless allowedAxioms.contains a do
            diags := diags.push (mk "axiom" s!"{ci.name} depends on disallowed axiom {a}")
        if let .axiomInfo _ := ci then
          diags := diags.push (mk "new-axiom" s!"{ci.name} is an axiom")
      out := out.push { gid, ok := diags.isEmpty, added, realized := nReal, diags, axioms := groupAxioms }
  return (out, sr)

end Paralean
