# Common settings for the P2 single-machine cluster. Source it; do not execute it.
# Everything lives under PARALEAN_P2_PREFIX (user space, no sudo).
export PARALEAN_P2_PREFIX="${PARALEAN_P2_PREFIX:-/data/home/kirancodes/paralean-p2}"

# Pinned versions.
export FDB_VERSION="${FDB_VERSION:-7.3.79}"
export GARAGE_VERSION="${GARAGE_VERSION:-2.4.1}"
# Garage publishes no checksum file; this is the SHA-256 of the v2.4.1
# x86_64-unknown-linux-musl binary as first downloaded on 2026-10-06.
export GARAGE_SHA256="${GARAGE_SHA256:-ae49f8de4aaee6b5ca305f7cbdccc8cd8a29b2804aac074649f18bfb83d0a2b6}"

# Ports chosen to avoid the defaults of FoundationDB (4500) and Garage (3900-3903)
# and everything else listening on the shared box.
export PARALEAN_FDB_PORT="${PARALEAN_FDB_PORT:-4689}"
export PARALEAN_GARAGE_S3_PORT="${PARALEAN_GARAGE_S3_PORT:-18439}"
export PARALEAN_GARAGE_RPC_PORT="${PARALEAN_GARAGE_RPC_PORT:-18440}"
export PARALEAN_GARAGE_ADMIN_PORT="${PARALEAN_GARAGE_ADMIN_PORT:-18441}"
# The delete-denying S3 gateway (s3-guard) in front of Garage; clients use this one.
export PARALEAN_S3_PORT="${PARALEAN_S3_PORT:-18433}"

export PARALEAN_FDB_CLUSTER="${PARALEAN_FDB_CLUSTER:-$PARALEAN_P2_PREFIX/fdb/fdb.cluster}"
export PARALEAN_S3_ENDPOINT="${PARALEAN_S3_ENDPOINT:-http://127.0.0.1:$PARALEAN_S3_PORT}"
export PARALEAN_S3_BUCKET="${PARALEAN_S3_BUCKET:-paralean}"
export PARALEAN_S3_REGION="${PARALEAN_S3_REGION:-garage}"

# Credentials generated by bootstrap.sh (Garage RPC secret, admin token, app key).
if [ -f "$PARALEAN_P2_PREFIX/garage/credentials.sh" ]; then
  . "$PARALEAN_P2_PREFIX/garage/credentials.sh"
fi

export PATH="$PARALEAN_P2_PREFIX/bin:$HOME/.cargo/bin:$PATH"
# libfdb_c.so for linking (LIBRARY_PATH) and at run time (LD_LIBRARY_PATH).
export LIBRARY_PATH="$PARALEAN_P2_PREFIX/lib${LIBRARY_PATH:+:$LIBRARY_PATH}"
export LD_LIBRARY_PATH="$PARALEAN_P2_PREFIX/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
