# Common settings for the P2 single-machine cluster. Source it; do not execute it.
# Everything lives under PARALEAN_P2_PREFIX (user space, no sudo).
export PARALEAN_P2_PREFIX="${PARALEAN_P2_PREFIX:-/data/home/kirancodes/paralean-p2}"

# Pinned versions.
export FDB_VERSION="${FDB_VERSION:-7.3.79}"
export GARAGE_VERSION="${GARAGE_VERSION:-2.4.1}"
# Garage publishes no checksum file; this is the SHA-256 of the v2.4.1
# x86_64-unknown-linux-musl binary as first downloaded on 2026-10-06.
export GARAGE_SHA256="${GARAGE_SHA256:-ae49f8de4aaee6b5ca305f7cbdccc8cd8a29b2804aac074649f18bfb83d0a2b6}"

# Instances. Unset PARALEAN_INSTANCE: the default cluster, with the ports and paths below.
# PARALEAN_INSTANCE=<name>: a separate cluster with its own data, run directory, credentials
# and ports under $PARALEAN_P2_PREFIX/inst/<name> (PARALEAN_HOME). Its settings are fixed on
# first start by up.sh and saved in $PARALEAN_HOME/instance.sh, which is sourced here; the
# first start needs PARALEAN_PORT_BASE (ports base..base+50) and optionally
# PARALEAN_FDB_PROCS, PARALEAN_FDB_REDUNDANCY, PARALEAN_FDB_COORDINATORS, PARALEAN_NETSPLIT,
# PARALEAN_GARAGE_NODES and PARALEAN_GARAGE_REPLICATION.
export PARALEAN_INSTANCE="${PARALEAN_INSTANCE:-}"
if [ -n "$PARALEAN_INSTANCE" ]; then
  export PARALEAN_HOME="$PARALEAN_P2_PREFIX/inst/$PARALEAN_INSTANCE"
  if [ -f "$PARALEAN_HOME/instance.sh" ]; then
    . "$PARALEAN_HOME/instance.sh"
  elif [ -n "${PARALEAN_PORT_BASE:-}" ]; then
    b="$PARALEAN_PORT_BASE"
    export PARALEAN_FDB_PORT=$b PARALEAN_GARAGE_S3_PORT=$((b + 20)) PARALEAN_GARAGE_RPC_PORT=$((b + 30))
    export PARALEAN_GARAGE_ADMIN_PORT=$((b + 40)) PARALEAN_S3_PORT=$((b + 50))
    export PARALEAN_FDB_CLUSTER="$PARALEAN_HOME/fdb/fdb.cluster"
    export PARALEAN_S3_ENDPOINT="http://127.0.0.1:$PARALEAN_S3_PORT"
    unset b
  else
    echo "env.sh: instance $PARALEAN_INSTANCE has no instance.sh yet; set PARALEAN_PORT_BASE" >&2
  fi
else
  export PARALEAN_HOME="$PARALEAN_P2_PREFIX"
fi
# Cluster shape (instances only; the default cluster is one fdbserver and one Garage node).
# FDB process i has public port PARALEAN_FDB_PORT+i; with netsplit its private port is
# PARALEAN_FDB_PORT+10+i. Garage node j uses the S3/RPC/admin ports above plus j.
export PARALEAN_FDB_PROCS="${PARALEAN_FDB_PROCS:-1}"
export PARALEAN_FDB_REDUNDANCY="${PARALEAN_FDB_REDUNDANCY:-single}"
export PARALEAN_FDB_COORDINATORS="${PARALEAN_FDB_COORDINATORS:-1}"
export PARALEAN_NETSPLIT="${PARALEAN_NETSPLIT:-0}"
export PARALEAN_GARAGE_NODES="${PARALEAN_GARAGE_NODES:-1}"
export PARALEAN_GARAGE_REPLICATION="${PARALEAN_GARAGE_REPLICATION:-1}"

# Ports chosen to avoid the defaults of FoundationDB (4500) and Garage (3900-3903)
# and everything else listening on the shared box.
export PARALEAN_FDB_PORT="${PARALEAN_FDB_PORT:-4689}"
export PARALEAN_GARAGE_S3_PORT="${PARALEAN_GARAGE_S3_PORT:-18439}"
export PARALEAN_GARAGE_RPC_PORT="${PARALEAN_GARAGE_RPC_PORT:-18440}"
export PARALEAN_GARAGE_ADMIN_PORT="${PARALEAN_GARAGE_ADMIN_PORT:-18441}"
# The delete-denying S3 gateway (s3-guard) in front of Garage; clients use this one.
export PARALEAN_S3_PORT="${PARALEAN_S3_PORT:-18433}"

export PARALEAN_FDB_CLUSTER="${PARALEAN_FDB_CLUSTER:-$PARALEAN_HOME/fdb/fdb.cluster}"
export PARALEAN_S3_ENDPOINT="${PARALEAN_S3_ENDPOINT:-http://127.0.0.1:$PARALEAN_S3_PORT}"
export PARALEAN_S3_BUCKET="${PARALEAN_S3_BUCKET:-paralean}"
export PARALEAN_S3_REGION="${PARALEAN_S3_REGION:-garage}"

# Credentials generated by bootstrap.sh (Garage RPC secret, admin token, app key).
if [ -f "$PARALEAN_HOME/garage/credentials.sh" ]; then
  . "$PARALEAN_HOME/garage/credentials.sh"
fi

export PATH="$PARALEAN_P2_PREFIX/bin:$HOME/.cargo/bin:$PATH"
# libfdb_c.so for linking (LIBRARY_PATH) and at run time (LD_LIBRARY_PATH).
export LIBRARY_PATH="$PARALEAN_P2_PREFIX/lib${LIBRARY_PATH:+:$LIBRARY_PATH}"
export LD_LIBRARY_PATH="$PARALEAN_P2_PREFIX/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
